cc_binary(
    name = "remote",
    srcs = ["remote.cc"],
    visibility = ["//visibility:public"],
    deps = ["//submodule/src/remote"],
)

cc_binary(
    name = "bare",
    srcs = ["bare.cc"],
    visibility = ["//visibility:public"],
    deps = ["//submodule/src:bare"],
)
